[package]
name = "stylus-test"
keywords = ["arbitrum", "ethereum", "stylus", "alloy"]
description = "Testing utilities for Arbitrum Stylus contracts"
readme = "../README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
stylus-core.workspace = true
rclite.workspace = true
tokio = { version = "1.12.0", features = ["full"] }
alloy-provider = "0.11.0"
url = "2.5.4"

[dev-dependencies]

[features]
default = []
reentrant = []
